# Generated by Django 4.1.1 on 2022-09-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=150)),
                ('lat_lon', models.CharField(max_length=50)),
                ('work_time', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('selected', 'Tanlangan'), ('finished', 'Yopilgan')], default='new', max_length=25)),
                ('doer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('offers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Takliflar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workss', to=settings.AUTH_USER_MODEL, verbose_name='Ish beruvchi')),
            ],
        ),
    ]
