# Generated by Django 3.1.14 on 2022-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('weight', models.CharField(max_length=10)),
                ('from_adrress', models.CharField(max_length=255)),
                ('from_floor', models.PositiveIntegerField()),
                ('from_kv', models.PositiveIntegerField(verbose_name=15)),
                ('from_persons', models.PositiveIntegerField()),
                ('to_adrress', models.CharField(max_length=255)),
                ('to_floor', models.PositiveIntegerField()),
                ('to_kv', models.PositiveIntegerField(verbose_name=15)),
                ('to_persons', models.PositiveIntegerField()),
                ('when', models.DateField()),
                ('description', models.TextField(verbose_name='Tafsilot')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('sent', "Yo'lda"), ('finished', 'Yopilgan')], default='new', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
