# Generated by Django 3.1.14 on 2022-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(choices=[('null', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich'), ('worker', 'Ishchi')], default='null', max_length=100),
        ),
    ]
