# Generated by Django 3.1.14 on 2022-05-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verifyemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifyemail',
            options={'verbose_name': 'Email tasdiqlash', 'verbose_name_plural': 'Email tasdiqlash'},
        ),
    ]
