# Generated by Django 3.1.14 on 2022-05-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220506_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.user', verbose_name='Foydalanuvchi'),
            preserve_default=False,
        ),
    ]
