# Generated by Django 3.1.14 on 2022-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220511_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(choices=[('n', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich'), ('worker', 'Ishchi')], default='n', max_length=100, null=True),
        ),
    ]
