# Generated by Django 3.1.14 on 2022-05-12 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220511_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='from_adrress',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='to_adrress',
            new_name='to_address',
        ),
        migrations.AddField(
            model_name='cargo',
            name='offers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Takliflar'),
        ),
    ]
