# Generated by Django 3.1.14 on 2022-05-12 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220512_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Takliflar'),
        ),
    ]
