# Generated by Django 3.1.14 on 2022-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220512_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(choices=[('disabled', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich')], default='disabled', max_length=100, null=True),
        ),
    ]
