# Generated by Django 3.1.14 on 2022-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220512_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Test uchun',
                'verbose_name_plural': 'Test uchun',
                'db_table': 'test',
            },
        ),
    ]
