# Generated by Django 4.0.4 on 2022-06-04 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_car_id_alter_cargo_id_alter_testmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
