# Generated by Django 4.0.4 on 2022-06-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Ishlar soni'),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.FloatField(default=0, verbose_name='Umumiy ball'),
        ),
    ]
