# Generated by Django 4.0.4 on 2022-06-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_count_user_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='when',
            new_name='time_when',
        ),
    ]
