# Generated by Django 4.0.4 on 2022-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_cargo_time_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Ishlar soni'),
        ),
    ]
