# Generated by Django 4.0.4 on 2022-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='doer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
