# Generated by Django 4.0.4 on 2022-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_user_gender_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
