# Generated by Django 4.0.4 on 2022-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_cargo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
