# Generated by Django 4.0.4 on 2022-06-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_cargo_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
