# Generated by Django 4.0.4 on 2022-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('finished', 'Yopilgan')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='time_when',
            field=models.DateField(),
        ),
    ]
