# Generated by Django 4.0.4 on 2022-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drive_license',
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_doc',
            field=models.CharField(max_length=50, verbose_name='Guvohnoma'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tech_inspect',
            field=models.CharField(max_length=50, verbose_name='Texnik passport'),
        ),
    ]
