# Generated by Django 4.0.4 on 2022-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_car_drive_license_alter_car_drive_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_doc',
            field=models.ImageField(upload_to='', verbose_name='Guvohnoma'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tech_inspect',
            field=models.ImageField(upload_to='', verbose_name='Texnik passport'),
        ),
    ]
