# Generated by Django 4.0.4 on 2022-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_car_drive_doc_alter_car_tech_inspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Mashina rasmi'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Mashina rasmi'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_type',
            field=models.CharField(choices=[('1', 'Kichik'), ('2', "O'rta"), ('3', 'Katta')], default='1', max_length=15, verbose_name='Mashina turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='drive_doc',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Guvohnoma'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
