# Generated by Django 4.0.4 on 2022-06-13 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_user_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
