# Generated by Django 4.0.4 on 2022-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_cargo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
