# Generated by Django 4.0.4 on 2022-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_user_account_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
