# Generated by Django 4.0.4 on 2022-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_cargo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_type_en',
            field=models.CharField(choices=[('disabled', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich')], default='disabled', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_type_ru',
            field=models.CharField(choices=[('disabled', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich')], default='disabled', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_type_uz',
            field=models.CharField(choices=[('disabled', 'Tanlanmagan'), ('small', 'Kichik'), ('big', 'Katta'), ('ice_car', 'Sovutgich')], default='disabled', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tafsilot'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='status_en',
            field=models.CharField(choices=[('new', 'Yangi'), ('finished', 'Yopilgan')], default='new', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='status_ru',
            field=models.CharField(choices=[('new', 'Yangi'), ('finished', 'Yopilgan')], default='new', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='status_uz',
            field=models.CharField(choices=[('new', 'Yangi'), ('finished', 'Yopilgan')], default='new', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
