# Generated by Django 4.0.4 on 2022-06-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_cargo_cargo_type_en_cargo_cargo_type_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_type_en',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_type_ru',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cargo_type_uz',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='status_uz',
        ),
    ]
