# Generated by Django 3.1.14 on 2022-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20220624_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('selected', 'Tanlangan'), ('finished', 'Yopilgan')], default='new', max_length=25),
        ),
    ]
