# Generated by Django 3.1.14 on 2022-06-24 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20220624_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=150)),
                ('work_time', models.CharField(max_length=55)),
                ('description', models.TextField(verbose_name='Tafsilot')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('selected', 'Tanlangan'), ('finished', 'Yopilgan')], default='new', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ish beruvchi')),
            ],
        ),
    ]
