# Generated by Django 3.1.14 on 2022-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='address_from',
            field=models.CharField(default='Tashkent', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='address_to',
            field=models.CharField(default='Tashkent', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='lat_lon',
            field=models.CharField(default='41.5478906,69.3873954', max_length=50),
            preserve_default=False,
        ),
    ]
