# Generated by Django 3.1.14 on 2022-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20220625_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='doer',
            field=models.CharField(max_length=25),
        ),
    ]
