# Generated by Django 3.1.14 on 2022-06-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20220625_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workes', to=settings.AUTH_USER_MODEL),
        ),
    ]
