# Generated by Django 3.1.14 on 2022-06-27 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20220627_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
