# Generated by Django 3.1.14 on 2022-06-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20220627_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workss', to=settings.AUTH_USER_MODEL, verbose_name='Ish beruvchi'),
        ),
    ]
