# Generated by Django 3.1.14 on 2022-06-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_work_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='doer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='user.user', verbose_name='Bajaruvchi'),
            preserve_default=False,
        ),
    ]
