# Generated by Django 3.1.14 on 2022-06-29 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_work_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='doer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi'),
        ),
    ]
