# Generated by Django 3.1.14 on 2022-07-06 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20220629_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
