# Generated by Django 3.1.14 on 2022-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20220706_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=100, null=True),
        ),
    ]
