# Generated by Django 3.1.14 on 2022-07-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20220725_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(default=293879, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
