# Generated by Django 3.1.14 on 2022-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_auto_20220730_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
