# Generated by Django 3.1.14 on 2022-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_auto_20220730_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='from_floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='to_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
