# Generated by Django 3.1.14 on 2022-08-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20220811_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='email',
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='phone',
            field=models.CharField(default=9989, max_length=15, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
    ]
