# Generated by Django 4.0.4 on 2022-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_cargo_id_alter_user_id_alter_verifyemail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='0', max_length=15, verbose_name='Mashina turi'),
        ),
    ]
