# Generated by Django 4.0.4 on 2022-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_user_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Mashina raqami'),
        ),
    ]
