# Generated by Django 4.0.4 on 2022-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_alter_user_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
