# Generated by Django 4.0.4 on 2022-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_verifyemail_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveIntegerField(verbose_name='Card number')),
                ('account', models.CharField(max_length=10, verbose_name='Account id')),
            ],
        ),
    ]
