# Generated by Django 4.0.4 on 2022-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_carddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='card',
            field=models.CharField(max_length=20, verbose_name='Card number'),
        ),
    ]
