# Generated by Django 4.1.1 on 2022-09-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_paymetransaction_alter_carddata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymeTransaction',
        ),
    ]
