# Generated by Django 4.1.1 on 2022-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_delete_paymetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='doer',
        ),
        migrations.RemoveField(
            model_name='work',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
