# Generated by Django 4.1.2 on 2022-10-12 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_remove_work_doer_remove_work_offers_remove_work_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
