# Generated by Django 4.1.1 on 2022-09-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('weight', models.PositiveIntegerField()),
                ('from_address', models.CharField(max_length=255)),
                ('address_from', models.CharField(max_length=255)),
                ('from_floor', models.PositiveIntegerField(default=0)),
                ('from_kv', models.PositiveIntegerField()),
                ('to_address', models.CharField(max_length=255)),
                ('address_to', models.CharField(max_length=255)),
                ('to_floor', models.PositiveIntegerField(default=0)),
                ('to_kv', models.PositiveIntegerField()),
                ('time_when', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tafsilot')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('selected', 'Tanlangan'), ('finished', 'Yopilgan')], default='new', max_length=25)),
                ('cargo_type', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=100, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workes', to=settings.AUTH_USER_MODEL)),
                ('offers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Takliflar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Jo'natma",
                'verbose_name_plural': "Jo'natmalar",
            },
        ),
    ]
